#!/usr/bin/make -f

all:
	make -C gm_config
	make -C gm_default
	make -C gm_sbuffer
	make -C gm_squeue
	make -C gm_timer
	make -C gm_transac

clean:
	make -C gm_config clean	
	make -C gm_default clean
	make -C gm_sbuffer clean
	make -C gm_squeue clean
	make -C gm_timer clean
	make -C gm_transac clean

install:
	make -C gm_config install
	make -C gm_default install
	make -C gm_sbuffer install
	make -C gm_squeue install
	make -C gm_timer install
	make -C gm_transac install

uninstall:
	make -C gm_config uninstall
	make -C gm_default uninstall
	make -C gm_sbuffer uninstall
	make -C gm_squeue uninstall
	make -C gm_timer uninstall
	make -C gm_transac uninstall
