#!/usr/bin/make -f

all:
	make -C gm_des
	make -C gm_loglevel
	make -C gm_safcfg
	make -C gm_viewcfg

clean:
	make -C gm_des clean
	make -C gm_loglevel clean
	make -C gm_safcfg clean
	make -C gm_viewcfg clean

install:
	make -C gm_des install
	make -C gm_loglevel install
	make -C gm_safcfg install
	make -C gm_viewcfg install

uninstall:
	make -C gm_des uninstall
	make -C gm_loglevel uninstall
	make -C gm_safcfg uninstall
	make -C gm_viewcfg uninstall
