#!/bin/sh

if [ -f /etc/gmonitor ]; then
  . /etc/gmonitor
else
  if [ -f /etc/sysconfig/gmonitor ]; then
    . /etc/sysconfig/gmonitor
  else
    if [ -f /usr/etc/gmonitor ]; then
      . /usr/etc/gmonitor
    else
      if [ -f /usr/etc/sysconfig/gmonitor ]; then
        . /usr/etc/sysconfig/gmonitor
      fi
    fi
  fi
fi

stat_proccess()
{
        x=`${PS_EAF} | grep -v grep | grep -v gmon_status | grep "${1}"`
	if [ "X${x}" != "X" ]
	then
		printf "Started\n"
	else
		printf "Down\n"
	fi
}

stat_one_service()
{
	servicio=`grep "^${1}|" $SERVER_CONF/server.tab | awk -F'|' '{ print $1 }'`
	descripcion=`grep "^${1}|" $SERVER_CONF/server.tab | awk -F'|' '{ print $2 }'`
	modo=`grep "^${1}|" $SERVER_CONF/server.tab | awk -F'|' '{ print $3 }'`
	server=`grep "^${1}|" $SERVER_CONF/server.tab | awk -F'|' '{ print $4 }'`

	if [ "X${servicio}" = "X" ]
	then
		exit 1
	fi

       	echo -n "Estado: [${servicio}] ${descripcion}             "
    
	if [ "X${modo}" = "X0" ] || [ "X${modo}" = "X1" ]
        then
        	stat_proccess "$SERVER_BIN/gmq -n $servicio"
        else
        	stat_proccess "$server -n $servicio"
        fi
}

stat_all_services()
{
        cat $SERVER_CONF/server.tab | grep -v "^#" | while read line
        do
                if [ "X"`echo $line | sed 's/\ //g' ` != "X" ]
                then
                        servicio=`echo $line | awk -F'|' '{ print $1 }'`
                        descripcion=`echo $line | awk -F'|' '{ print $2 }'`
                        modo=`echo $line | awk -F'|' '{ print $3 }'`
                        server=`echo $line | awk -F'|' '{ print $4 }'`

       			printf "Estado: [%-15.15s] %-35.35s    " "${servicio}" "${descripcion}"
    
			if [ "X${modo}" = "X0" ] || [ "X${modo}" = "X1" ]
        		then
        			stat_proccess "$SERVER_BIN/gmq -n $servicio"
        		else
        			stat_proccess "$server -n $servicio"
        		fi
		fi
        done
}

if [ "X${1}" = "Xall" ] || [ "X${1}" = "XALL" ]
then
	stat_all_services
else
	stat_one_service $1
fi

